// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "yuv2rgb.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic yuv2rgb::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic yuv2rgb::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> yuv2rgb::ap_ST_fsm_state1 = "1";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state2 = "10";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state3 = "100";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state4 = "1000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state5 = "10000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state6 = "100000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> yuv2rgb::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> yuv2rgb::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> yuv2rgb::ap_const_lv32_1 = "1";
const sc_lv<1> yuv2rgb::ap_const_lv1_0 = "0";
const sc_lv<32> yuv2rgb::ap_const_lv32_2 = "10";
const sc_lv<32> yuv2rgb::ap_const_lv32_3 = "11";
const sc_lv<32> yuv2rgb::ap_const_lv32_5 = "101";
const sc_lv<32> yuv2rgb::ap_const_lv32_6 = "110";
const sc_lv<32> yuv2rgb::ap_const_lv32_7 = "111";
const sc_lv<32> yuv2rgb::ap_const_lv32_8 = "1000";
const sc_lv<16> yuv2rgb::ap_const_lv16_0 = "0000000000000000";
const sc_lv<1> yuv2rgb::ap_const_lv1_1 = "1";
const sc_lv<32> yuv2rgb::ap_const_lv32_9 = "1001";
const sc_lv<32> yuv2rgb::ap_const_lv32_4 = "100";
const sc_lv<16> yuv2rgb::ap_const_lv16_1 = "1";
const sc_lv<10> yuv2rgb::ap_const_lv10_0 = "0000000000";
const sc_lv<8> yuv2rgb::ap_const_lv8_0 = "00000000";
const sc_lv<8> yuv2rgb::ap_const_lv8_80 = "10000000";
const sc_lv<17> yuv2rgb::ap_const_lv17_1FF30 = "11111111100110000";
const sc_lv<32> yuv2rgb::ap_const_lv32_10 = "10000";
const sc_lv<32> yuv2rgb::ap_const_lv32_11 = "10001";
const sc_lv<2> yuv2rgb::ap_const_lv2_1 = "1";
const sc_lv<32> yuv2rgb::ap_const_lv32_F = "1111";
const sc_lv<8> yuv2rgb::ap_const_lv8_FF = "11111111";
const sc_lv<9> yuv2rgb::ap_const_lv9_0 = "000000000";
const sc_lv<2> yuv2rgb::ap_const_lv2_0 = "00";
const sc_lv<32> yuv2rgb::ap_const_lv32_12 = "10010";
const sc_lv<3> yuv2rgb::ap_const_lv3_0 = "000";
const sc_lv<9> yuv2rgb::ap_const_lv9_1F0 = "111110000";
const sc_lv<18> yuv2rgb::ap_const_lv18_12A = "100101010";
const sc_lv<18> yuv2rgb::ap_const_lv18_80 = "10000000";
const sc_lv<18> yuv2rgb::ap_const_lv18_199 = "110011001";
const sc_lv<16> yuv2rgb::ap_const_lv16_FF9C = "1111111110011100";
const bool yuv2rgb::ap_const_boolean_1 = true;

yuv2rgb::yuv2rgb(sc_module_name name) : sc_module(name), mVcdFile(0) {
    yuv_filter_ama_adeOg_U15 = new yuv_filter_ama_adeOg<1,1,5,8,18,18,18>("yuv_filter_ama_adeOg_U15");
    yuv_filter_ama_adeOg_U15->din0(grp_fu_537_p0);
    yuv_filter_ama_adeOg_U15->din1(grp_fu_537_p1);
    yuv_filter_ama_adeOg_U15->din2(ap_var_for_const0);
    yuv_filter_ama_adeOg_U15->din3(ap_var_for_const1);
    yuv_filter_ama_adeOg_U15->dout(grp_fu_537_p4);
    yuv_filter_mac_mufYi_U16 = new yuv_filter_mac_mufYi<1,1,10,8,18,18>("yuv_filter_mac_mufYi_U16");
    yuv_filter_mac_mufYi_U16->din0(grp_fu_547_p0);
    yuv_filter_mac_mufYi_U16->din1(E_reg_634);
    yuv_filter_mac_mufYi_U16->din2(tmp_3_reg_639);
    yuv_filter_mac_mufYi_U16->dout(grp_fu_547_p3);
    yuv_filter_mac_mug8j_U17 = new yuv_filter_mac_mug8j<1,1,8,8,17,17>("yuv_filter_mac_mug8j_U17");
    yuv_filter_mac_mug8j_U17->din0(grp_fu_557_p0);
    yuv_filter_mac_mug8j_U17->din1(D_reg_627);
    yuv_filter_mac_mug8j_U17->din2(tmp_13_reg_646);
    yuv_filter_mac_mug8j_U17->dout(grp_fu_557_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_B_fu_529_p3);
    sensitive << ( tmp_21_fu_523_p2 );
    sensitive << ( p_phitmp3_fu_515_p3 );
    sensitive << ( phitmp3_fu_505_p4 );

    SC_METHOD(thread_D_fu_299_p2);
    sensitive << ( in_channels_ch2_q0 );

    SC_METHOD(thread_E_fu_305_p2);
    sensitive << ( in_channels_ch3_q0 );

    SC_METHOD(thread_G_fu_436_p3);
    sensitive << ( tmp_17_fu_430_p2 );
    sensitive << ( p_phitmp2_fu_422_p3 );
    sensitive << ( phitmp2_fu_412_p4 );

    SC_METHOD(thread_R_fu_369_p3);
    sensitive << ( tmp_11_fu_363_p2 );
    sensitive << ( p_phitmp_fu_355_p3 );
    sensitive << ( phitmp_fu_346_p4 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_220_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_220_p2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_220_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_220_p2 );

    SC_METHOD(thread_exitcond1_fu_220_p2);
    sensitive << ( in_width_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_reg_198 );

    SC_METHOD(thread_exitcond_fu_271_p2);
    sensitive << ( in_height_read );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_reg_209 );

    SC_METHOD(thread_grp_fu_537_p0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_537_p1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_537_p10 );

    SC_METHOD(thread_grp_fu_537_p10);
    sensitive << ( Y_reg_622 );

    SC_METHOD(thread_grp_fu_547_p0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_557_p0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_icmp1_fu_491_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_19_fu_481_p4 );

    SC_METHOD(thread_icmp9_fu_398_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_15_fu_388_p4 );

    SC_METHOD(thread_icmp_fu_333_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_8_fu_324_p4 );

    SC_METHOD(thread_in_channels_ch1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_291_p1 );

    SC_METHOD(thread_in_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch2_address0);
    sensitive << ( tmp_21_cast_reg_598 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_in_channels_ch3_address0);
    sensitive << ( tmp_21_cast_reg_598 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_out_channels_ch1_address0);
    sensitive << ( tmp_21_cast_reg_598 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch1_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch1_d0);
    sensitive << ( R_reg_651 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch1_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_address0);
    sensitive << ( tmp_21_cast_reg_598 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch2_d0);
    sensitive << ( G_reg_656 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch2_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_address0);
    sensitive << ( tmp_21_cast_reg_598 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_channels_ch3_d0);
    sensitive << ( B_reg_661 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_channels_ch3_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_p_phitmp2_fu_422_p3);
    sensitive << ( icmp9_fu_398_p2 );

    SC_METHOD(thread_p_phitmp3_fu_515_p3);
    sensitive << ( icmp1_fu_491_p2 );

    SC_METHOD(thread_p_phitmp_fu_355_p3);
    sensitive << ( icmp_fu_333_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_462_p1);
    sensitive << ( p_shl1_fu_455_p3 );

    SC_METHOD(thread_p_shl1_fu_455_p3);
    sensitive << ( D_reg_627 );

    SC_METHOD(thread_p_shl2_cast_fu_235_p3);
    sensitive << ( tmp_fu_231_p1 );

    SC_METHOD(thread_p_shl3_cast_fu_247_p3);
    sensitive << ( tmp_5_fu_243_p1 );

    SC_METHOD(thread_p_shl_cast_fu_451_p1);
    sensitive << ( p_shl_fu_444_p3 );

    SC_METHOD(thread_p_shl_fu_444_p3);
    sensitive << ( D_reg_627 );

    SC_METHOD(thread_phitmp2_fu_412_p4);
    sensitive << ( tmp_14_fu_383_p2 );

    SC_METHOD(thread_phitmp3_fu_505_p4);
    sensitive << ( tmp_18_fu_475_p2 );

    SC_METHOD(thread_phitmp_fu_346_p4);
    sensitive << ( grp_fu_547_p3 );

    SC_METHOD(thread_tmp1_cast_fu_380_p1);
    sensitive << ( grp_fu_557_p3 );

    SC_METHOD(thread_tmp2_cast_fu_471_p1);
    sensitive << ( tmp2_fu_466_p2 );

    SC_METHOD(thread_tmp2_fu_466_p2);
    sensitive << ( tmp_3_reg_639 );
    sensitive << ( p_shl1_cast_fu_462_p1 );

    SC_METHOD(thread_tmp_10_fu_339_p3);
    sensitive << ( grp_fu_547_p3 );

    SC_METHOD(thread_tmp_11_fu_363_p2);
    sensitive << ( icmp_fu_333_p2 );
    sensitive << ( tmp_10_fu_339_p3 );

    SC_METHOD(thread_tmp_13_fu_315_p1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( E_fu_305_p2 );

    SC_METHOD(thread_tmp_13_fu_315_p2);
    sensitive << ( tmp_13_fu_315_p1 );

    SC_METHOD(thread_tmp_14_fu_383_p2);
    sensitive << ( tmp_3_reg_639 );
    sensitive << ( tmp1_cast_fu_380_p1 );

    SC_METHOD(thread_tmp_15_fu_388_p4);
    sensitive << ( tmp_14_fu_383_p2 );

    SC_METHOD(thread_tmp_16_fu_404_p3);
    sensitive << ( tmp_14_fu_383_p2 );

    SC_METHOD(thread_tmp_17_fu_430_p2);
    sensitive << ( icmp9_fu_398_p2 );
    sensitive << ( tmp_16_fu_404_p3 );

    SC_METHOD(thread_tmp_18_fu_475_p2);
    sensitive << ( tmp2_cast_fu_471_p1 );
    sensitive << ( p_shl_cast_fu_451_p1 );

    SC_METHOD(thread_tmp_19_fu_481_p4);
    sensitive << ( tmp_18_fu_475_p2 );

    SC_METHOD(thread_tmp_20_fu_497_p3);
    sensitive << ( tmp_18_fu_475_p2 );

    SC_METHOD(thread_tmp_21_cast_fu_291_p1);
    sensitive << ( tmp_6_fu_286_p2 );

    SC_METHOD(thread_tmp_21_fu_523_p2);
    sensitive << ( icmp1_fu_491_p2 );
    sensitive << ( tmp_20_fu_497_p3 );

    SC_METHOD(thread_tmp_5_fu_243_p1);
    sensitive << ( x_reg_198 );

    SC_METHOD(thread_tmp_6_fu_286_p2);
    sensitive << ( tmp_s_reg_585 );
    sensitive << ( tmp_cast_fu_282_p1 );

    SC_METHOD(thread_tmp_8_fu_324_p4);
    sensitive << ( grp_fu_547_p3 );

    SC_METHOD(thread_tmp_cast_fu_282_p1);
    sensitive << ( y_reg_209 );

    SC_METHOD(thread_tmp_fu_231_p1);
    sensitive << ( x_reg_198 );

    SC_METHOD(thread_tmp_s_fu_255_p2);
    sensitive << ( p_shl2_cast_fu_235_p3 );
    sensitive << ( p_shl3_cast_fu_247_p3 );

    SC_METHOD(thread_x_1_fu_225_p2);
    sensitive << ( x_reg_198 );

    SC_METHOD(thread_y_1_fu_276_p2);
    sensitive << ( y_reg_209 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_220_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_271_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "yuv2rgb_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_channels_ch1_address0, "(port)in_channels_ch1_address0");
    sc_trace(mVcdFile, in_channels_ch1_ce0, "(port)in_channels_ch1_ce0");
    sc_trace(mVcdFile, in_channels_ch1_q0, "(port)in_channels_ch1_q0");
    sc_trace(mVcdFile, in_channels_ch2_address0, "(port)in_channels_ch2_address0");
    sc_trace(mVcdFile, in_channels_ch2_ce0, "(port)in_channels_ch2_ce0");
    sc_trace(mVcdFile, in_channels_ch2_q0, "(port)in_channels_ch2_q0");
    sc_trace(mVcdFile, in_channels_ch3_address0, "(port)in_channels_ch3_address0");
    sc_trace(mVcdFile, in_channels_ch3_ce0, "(port)in_channels_ch3_ce0");
    sc_trace(mVcdFile, in_channels_ch3_q0, "(port)in_channels_ch3_q0");
    sc_trace(mVcdFile, in_width_read, "(port)in_width_read");
    sc_trace(mVcdFile, in_height_read, "(port)in_height_read");
    sc_trace(mVcdFile, out_channels_ch1_address0, "(port)out_channels_ch1_address0");
    sc_trace(mVcdFile, out_channels_ch1_ce0, "(port)out_channels_ch1_ce0");
    sc_trace(mVcdFile, out_channels_ch1_we0, "(port)out_channels_ch1_we0");
    sc_trace(mVcdFile, out_channels_ch1_d0, "(port)out_channels_ch1_d0");
    sc_trace(mVcdFile, out_channels_ch2_address0, "(port)out_channels_ch2_address0");
    sc_trace(mVcdFile, out_channels_ch2_ce0, "(port)out_channels_ch2_ce0");
    sc_trace(mVcdFile, out_channels_ch2_we0, "(port)out_channels_ch2_we0");
    sc_trace(mVcdFile, out_channels_ch2_d0, "(port)out_channels_ch2_d0");
    sc_trace(mVcdFile, out_channels_ch3_address0, "(port)out_channels_ch3_address0");
    sc_trace(mVcdFile, out_channels_ch3_ce0, "(port)out_channels_ch3_ce0");
    sc_trace(mVcdFile, out_channels_ch3_we0, "(port)out_channels_ch3_we0");
    sc_trace(mVcdFile, out_channels_ch3_d0, "(port)out_channels_ch3_d0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, x_1_fu_225_p2, "x_1_fu_225_p2");
    sc_trace(mVcdFile, x_1_reg_580, "x_1_reg_580");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_s_fu_255_p2, "tmp_s_fu_255_p2");
    sc_trace(mVcdFile, tmp_s_reg_585, "tmp_s_reg_585");
    sc_trace(mVcdFile, exitcond1_fu_220_p2, "exitcond1_fu_220_p2");
    sc_trace(mVcdFile, y_1_fu_276_p2, "y_1_fu_276_p2");
    sc_trace(mVcdFile, y_1_reg_593, "y_1_reg_593");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_21_cast_fu_291_p1, "tmp_21_cast_fu_291_p1");
    sc_trace(mVcdFile, tmp_21_cast_reg_598, "tmp_21_cast_reg_598");
    sc_trace(mVcdFile, exitcond_fu_271_p2, "exitcond_fu_271_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, Y_reg_622, "Y_reg_622");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, D_fu_299_p2, "D_fu_299_p2");
    sc_trace(mVcdFile, D_reg_627, "D_reg_627");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, E_fu_305_p2, "E_fu_305_p2");
    sc_trace(mVcdFile, E_reg_634, "E_reg_634");
    sc_trace(mVcdFile, grp_fu_537_p4, "grp_fu_537_p4");
    sc_trace(mVcdFile, tmp_3_reg_639, "tmp_3_reg_639");
    sc_trace(mVcdFile, tmp_13_fu_315_p2, "tmp_13_fu_315_p2");
    sc_trace(mVcdFile, tmp_13_reg_646, "tmp_13_reg_646");
    sc_trace(mVcdFile, R_fu_369_p3, "R_fu_369_p3");
    sc_trace(mVcdFile, R_reg_651, "R_reg_651");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, G_fu_436_p3, "G_fu_436_p3");
    sc_trace(mVcdFile, G_reg_656, "G_reg_656");
    sc_trace(mVcdFile, B_fu_529_p3, "B_fu_529_p3");
    sc_trace(mVcdFile, B_reg_661, "B_reg_661");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, x_reg_198, "x_reg_198");
    sc_trace(mVcdFile, y_reg_209, "y_reg_209");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_fu_231_p1, "tmp_fu_231_p1");
    sc_trace(mVcdFile, tmp_5_fu_243_p1, "tmp_5_fu_243_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_235_p3, "p_shl2_cast_fu_235_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_247_p3, "p_shl3_cast_fu_247_p3");
    sc_trace(mVcdFile, tmp_cast_fu_282_p1, "tmp_cast_fu_282_p1");
    sc_trace(mVcdFile, tmp_6_fu_286_p2, "tmp_6_fu_286_p2");
    sc_trace(mVcdFile, tmp_13_fu_315_p1, "tmp_13_fu_315_p1");
    sc_trace(mVcdFile, grp_fu_547_p3, "grp_fu_547_p3");
    sc_trace(mVcdFile, tmp_8_fu_324_p4, "tmp_8_fu_324_p4");
    sc_trace(mVcdFile, icmp_fu_333_p2, "icmp_fu_333_p2");
    sc_trace(mVcdFile, tmp_10_fu_339_p3, "tmp_10_fu_339_p3");
    sc_trace(mVcdFile, tmp_11_fu_363_p2, "tmp_11_fu_363_p2");
    sc_trace(mVcdFile, p_phitmp_fu_355_p3, "p_phitmp_fu_355_p3");
    sc_trace(mVcdFile, phitmp_fu_346_p4, "phitmp_fu_346_p4");
    sc_trace(mVcdFile, grp_fu_557_p3, "grp_fu_557_p3");
    sc_trace(mVcdFile, tmp1_cast_fu_380_p1, "tmp1_cast_fu_380_p1");
    sc_trace(mVcdFile, tmp_14_fu_383_p2, "tmp_14_fu_383_p2");
    sc_trace(mVcdFile, tmp_15_fu_388_p4, "tmp_15_fu_388_p4");
    sc_trace(mVcdFile, icmp9_fu_398_p2, "icmp9_fu_398_p2");
    sc_trace(mVcdFile, tmp_16_fu_404_p3, "tmp_16_fu_404_p3");
    sc_trace(mVcdFile, tmp_17_fu_430_p2, "tmp_17_fu_430_p2");
    sc_trace(mVcdFile, p_phitmp2_fu_422_p3, "p_phitmp2_fu_422_p3");
    sc_trace(mVcdFile, phitmp2_fu_412_p4, "phitmp2_fu_412_p4");
    sc_trace(mVcdFile, p_shl_fu_444_p3, "p_shl_fu_444_p3");
    sc_trace(mVcdFile, p_shl1_fu_455_p3, "p_shl1_fu_455_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_462_p1, "p_shl1_cast_fu_462_p1");
    sc_trace(mVcdFile, tmp2_fu_466_p2, "tmp2_fu_466_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_471_p1, "tmp2_cast_fu_471_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_451_p1, "p_shl_cast_fu_451_p1");
    sc_trace(mVcdFile, tmp_18_fu_475_p2, "tmp_18_fu_475_p2");
    sc_trace(mVcdFile, tmp_19_fu_481_p4, "tmp_19_fu_481_p4");
    sc_trace(mVcdFile, icmp1_fu_491_p2, "icmp1_fu_491_p2");
    sc_trace(mVcdFile, tmp_20_fu_497_p3, "tmp_20_fu_497_p3");
    sc_trace(mVcdFile, tmp_21_fu_523_p2, "tmp_21_fu_523_p2");
    sc_trace(mVcdFile, p_phitmp3_fu_515_p3, "p_phitmp3_fu_515_p3");
    sc_trace(mVcdFile, phitmp3_fu_505_p4, "phitmp3_fu_505_p4");
    sc_trace(mVcdFile, grp_fu_537_p0, "grp_fu_537_p0");
    sc_trace(mVcdFile, grp_fu_537_p1, "grp_fu_537_p1");
    sc_trace(mVcdFile, grp_fu_547_p0, "grp_fu_547_p0");
    sc_trace(mVcdFile, grp_fu_557_p0, "grp_fu_557_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_537_p10, "grp_fu_537_p10");
#endif

    }
}

yuv2rgb::~yuv2rgb() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete yuv_filter_ama_adeOg_U15;
    delete yuv_filter_mac_mufYi_U16;
    delete yuv_filter_mac_mug8j_U17;
}

void yuv2rgb::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv18_12A;
}

void yuv2rgb::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv18_80;
}

void yuv2rgb::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_271_p2.read(), ap_const_lv1_1))) {
        x_reg_198 = x_1_reg_580.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_reg_198 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        y_reg_209 = y_1_reg_593.read();
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_220_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        y_reg_209 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        B_reg_661 = B_fu_529_p3.read();
        G_reg_656 = G_fu_436_p3.read();
        R_reg_651 = R_fu_369_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        D_reg_627 = D_fu_299_p2.read();
        E_reg_634 = E_fu_305_p2.read();
        tmp_13_reg_646 = tmp_13_fu_315_p2.read();
        tmp_3_reg_639 = grp_fu_537_p4.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        Y_reg_622 = in_channels_ch1_q0.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_271_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        tmp_21_cast_reg_598 = tmp_21_cast_fu_291_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_220_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_s_reg_585 = tmp_s_fu_255_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_1_reg_580 = x_1_fu_225_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_1_reg_593 = y_1_fu_276_p2.read();
    }
}

void yuv2rgb::thread_B_fu_529_p3() {
    B_fu_529_p3 = (!tmp_21_fu_523_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_21_fu_523_p2.read()[0].to_bool())? p_phitmp3_fu_515_p3.read(): phitmp3_fu_505_p4.read());
}

void yuv2rgb::thread_D_fu_299_p2() {
    D_fu_299_p2 = (in_channels_ch2_q0.read() ^ ap_const_lv8_80);
}

void yuv2rgb::thread_E_fu_305_p2() {
    E_fu_305_p2 = (in_channels_ch3_q0.read() ^ ap_const_lv8_80);
}

void yuv2rgb::thread_G_fu_436_p3() {
    G_fu_436_p3 = (!tmp_17_fu_430_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_17_fu_430_p2.read()[0].to_bool())? p_phitmp2_fu_422_p3.read(): phitmp2_fu_412_p4.read());
}

void yuv2rgb::thread_R_fu_369_p3() {
    R_fu_369_p3 = (!tmp_11_fu_363_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_11_fu_363_p2.read()[0].to_bool())? p_phitmp_fu_355_p3.read(): phitmp_fu_346_p4.read());
}

void yuv2rgb::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void yuv2rgb::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void yuv2rgb::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void yuv2rgb::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void yuv2rgb::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void yuv2rgb::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void yuv2rgb::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void yuv2rgb::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void yuv2rgb::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void yuv2rgb::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void yuv2rgb::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond1_fu_220_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond1_fu_220_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void yuv2rgb::thread_ap_return_0() {
    ap_return_0 = in_width_read.read();
}

void yuv2rgb::thread_ap_return_1() {
    ap_return_1 = in_height_read.read();
}

void yuv2rgb::thread_exitcond1_fu_220_p2() {
    exitcond1_fu_220_p2 = (!x_reg_198.read().is_01() || !in_width_read.read().is_01())? sc_lv<1>(): sc_lv<1>(x_reg_198.read() == in_width_read.read());
}

void yuv2rgb::thread_exitcond_fu_271_p2() {
    exitcond_fu_271_p2 = (!y_reg_209.read().is_01() || !in_height_read.read().is_01())? sc_lv<1>(): sc_lv<1>(y_reg_209.read() == in_height_read.read());
}

void yuv2rgb::thread_grp_fu_537_p0() {
    grp_fu_537_p0 =  (sc_lv<5>) (ap_const_lv9_1F0);
}

void yuv2rgb::thread_grp_fu_537_p1() {
    grp_fu_537_p1 =  (sc_lv<8>) (grp_fu_537_p10.read());
}

void yuv2rgb::thread_grp_fu_537_p10() {
    grp_fu_537_p10 = esl_zext<9,8>(Y_reg_622.read());
}

void yuv2rgb::thread_grp_fu_547_p0() {
    grp_fu_547_p0 =  (sc_lv<10>) (ap_const_lv18_199);
}

void yuv2rgb::thread_grp_fu_557_p0() {
    grp_fu_557_p0 =  (sc_lv<8>) (ap_const_lv16_FF9C);
}

void yuv2rgb::thread_icmp1_fu_491_p2() {
    icmp1_fu_491_p2 = (!tmp_19_fu_481_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): (sc_bigint<3>(tmp_19_fu_481_p4.read()) > sc_bigint<3>(ap_const_lv3_0));
}

void yuv2rgb::thread_icmp9_fu_398_p2() {
    icmp9_fu_398_p2 = (!tmp_15_fu_388_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_15_fu_388_p4.read() == ap_const_lv2_1);
}

void yuv2rgb::thread_icmp_fu_333_p2() {
    icmp_fu_333_p2 = (!tmp_8_fu_324_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_fu_324_p4.read() == ap_const_lv2_1);
}

void yuv2rgb::thread_in_channels_ch1_address0() {
    in_channels_ch1_address0 =  (sc_lv<22>) (tmp_21_cast_fu_291_p1.read());
}

void yuv2rgb::thread_in_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_in_channels_ch2_address0() {
    in_channels_ch2_address0 =  (sc_lv<22>) (tmp_21_cast_reg_598.read());
}

void yuv2rgb::thread_in_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_in_channels_ch3_address0() {
    in_channels_ch3_address0 =  (sc_lv<22>) (tmp_21_cast_reg_598.read());
}

void yuv2rgb::thread_in_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        in_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch1_address0() {
    out_channels_ch1_address0 =  (sc_lv<22>) (tmp_21_cast_reg_598.read());
}

void yuv2rgb::thread_out_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch1_d0() {
    out_channels_ch1_d0 = R_reg_651.read();
}

void yuv2rgb::thread_out_channels_ch1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch1_we0 = ap_const_logic_1;
    } else {
        out_channels_ch1_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch2_address0() {
    out_channels_ch2_address0 =  (sc_lv<22>) (tmp_21_cast_reg_598.read());
}

void yuv2rgb::thread_out_channels_ch2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch2_d0() {
    out_channels_ch2_d0 = G_reg_656.read();
}

void yuv2rgb::thread_out_channels_ch2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch2_we0 = ap_const_logic_1;
    } else {
        out_channels_ch2_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch3_address0() {
    out_channels_ch3_address0 =  (sc_lv<22>) (tmp_21_cast_reg_598.read());
}

void yuv2rgb::thread_out_channels_ch3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_out_channels_ch3_d0() {
    out_channels_ch3_d0 = B_reg_661.read();
}

void yuv2rgb::thread_out_channels_ch3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_channels_ch3_we0 = ap_const_logic_1;
    } else {
        out_channels_ch3_we0 = ap_const_logic_0;
    }
}

void yuv2rgb::thread_p_phitmp2_fu_422_p3() {
    p_phitmp2_fu_422_p3 = (!icmp9_fu_398_p2.read()[0].is_01())? sc_lv<8>(): ((icmp9_fu_398_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_p_phitmp3_fu_515_p3() {
    p_phitmp3_fu_515_p3 = (!icmp1_fu_491_p2.read()[0].is_01())? sc_lv<8>(): ((icmp1_fu_491_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_p_phitmp_fu_355_p3() {
    p_phitmp_fu_355_p3 = (!icmp_fu_333_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_fu_333_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv2rgb::thread_p_shl1_cast_fu_462_p1() {
    p_shl1_cast_fu_462_p1 = esl_sext<18,10>(p_shl1_fu_455_p3.read());
}

void yuv2rgb::thread_p_shl1_fu_455_p3() {
    p_shl1_fu_455_p3 = esl_concat<8,2>(D_reg_627.read(), ap_const_lv2_0);
}

void yuv2rgb::thread_p_shl2_cast_fu_235_p3() {
    p_shl2_cast_fu_235_p3 = esl_concat<13,10>(tmp_fu_231_p1.read(), ap_const_lv10_0);
}

void yuv2rgb::thread_p_shl3_cast_fu_247_p3() {
    p_shl3_cast_fu_247_p3 = esl_concat<15,8>(tmp_5_fu_243_p1.read(), ap_const_lv8_0);
}

void yuv2rgb::thread_p_shl_cast_fu_451_p1() {
    p_shl_cast_fu_451_p1 = esl_sext<19,17>(p_shl_fu_444_p3.read());
}

void yuv2rgb::thread_p_shl_fu_444_p3() {
    p_shl_fu_444_p3 = esl_concat<8,9>(D_reg_627.read(), ap_const_lv9_0);
}

void yuv2rgb::thread_phitmp2_fu_412_p4() {
    phitmp2_fu_412_p4 = tmp_14_fu_383_p2.read().range(15, 8);
}

void yuv2rgb::thread_phitmp3_fu_505_p4() {
    phitmp3_fu_505_p4 = tmp_18_fu_475_p2.read().range(15, 8);
}

void yuv2rgb::thread_phitmp_fu_346_p4() {
    phitmp_fu_346_p4 = grp_fu_547_p3.read().range(15, 8);
}

void yuv2rgb::thread_tmp1_cast_fu_380_p1() {
    tmp1_cast_fu_380_p1 = esl_sext<18,17>(grp_fu_557_p3.read());
}

void yuv2rgb::thread_tmp2_cast_fu_471_p1() {
    tmp2_cast_fu_471_p1 = esl_sext<19,18>(tmp2_fu_466_p2.read());
}

void yuv2rgb::thread_tmp2_fu_466_p2() {
    tmp2_fu_466_p2 = (!p_shl1_cast_fu_462_p1.read().is_01() || !tmp_3_reg_639.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_shl1_cast_fu_462_p1.read()) + sc_bigint<18>(tmp_3_reg_639.read()));
}

void yuv2rgb::thread_tmp_10_fu_339_p3() {
    tmp_10_fu_339_p3 = grp_fu_547_p3.read().range(17, 17);
}

void yuv2rgb::thread_tmp_11_fu_363_p2() {
    tmp_11_fu_363_p2 = (icmp_fu_333_p2.read() | tmp_10_fu_339_p3.read());
}

void yuv2rgb::thread_tmp_13_fu_315_p1() {
    tmp_13_fu_315_p1 = E_fu_305_p2.read();
}

void yuv2rgb::thread_tmp_13_fu_315_p2() {
    tmp_13_fu_315_p2 = (!ap_const_lv17_1FF30.is_01() || !tmp_13_fu_315_p1.read().is_01())? sc_lv<17>(): sc_bigint<17>(ap_const_lv17_1FF30) * sc_bigint<8>(tmp_13_fu_315_p1.read());
}

void yuv2rgb::thread_tmp_14_fu_383_p2() {
    tmp_14_fu_383_p2 = (!tmp1_cast_fu_380_p1.read().is_01() || !tmp_3_reg_639.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp1_cast_fu_380_p1.read()) + sc_bigint<18>(tmp_3_reg_639.read()));
}

void yuv2rgb::thread_tmp_15_fu_388_p4() {
    tmp_15_fu_388_p4 = tmp_14_fu_383_p2.read().range(17, 16);
}

void yuv2rgb::thread_tmp_16_fu_404_p3() {
    tmp_16_fu_404_p3 = tmp_14_fu_383_p2.read().range(17, 17);
}

void yuv2rgb::thread_tmp_17_fu_430_p2() {
    tmp_17_fu_430_p2 = (icmp9_fu_398_p2.read() | tmp_16_fu_404_p3.read());
}

void yuv2rgb::thread_tmp_18_fu_475_p2() {
    tmp_18_fu_475_p2 = (!tmp2_cast_fu_471_p1.read().is_01() || !p_shl_cast_fu_451_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(tmp2_cast_fu_471_p1.read()) + sc_bigint<19>(p_shl_cast_fu_451_p1.read()));
}

void yuv2rgb::thread_tmp_19_fu_481_p4() {
    tmp_19_fu_481_p4 = tmp_18_fu_475_p2.read().range(18, 16);
}

void yuv2rgb::thread_tmp_20_fu_497_p3() {
    tmp_20_fu_497_p3 = tmp_18_fu_475_p2.read().range(18, 18);
}

void yuv2rgb::thread_tmp_21_cast_fu_291_p1() {
    tmp_21_cast_fu_291_p1 = esl_zext<64,23>(tmp_6_fu_286_p2.read());
}

void yuv2rgb::thread_tmp_21_fu_523_p2() {
    tmp_21_fu_523_p2 = (icmp1_fu_491_p2.read() | tmp_20_fu_497_p3.read());
}

void yuv2rgb::thread_tmp_5_fu_243_p1() {
    tmp_5_fu_243_p1 = x_reg_198.read().range(15-1, 0);
}

void yuv2rgb::thread_tmp_6_fu_286_p2() {
    tmp_6_fu_286_p2 = (!tmp_cast_fu_282_p1.read().is_01() || !tmp_s_reg_585.read().is_01())? sc_lv<23>(): (sc_biguint<23>(tmp_cast_fu_282_p1.read()) + sc_biguint<23>(tmp_s_reg_585.read()));
}

void yuv2rgb::thread_tmp_8_fu_324_p4() {
    tmp_8_fu_324_p4 = grp_fu_547_p3.read().range(17, 16);
}

void yuv2rgb::thread_tmp_cast_fu_282_p1() {
    tmp_cast_fu_282_p1 = esl_zext<23,16>(y_reg_209.read());
}

void yuv2rgb::thread_tmp_fu_231_p1() {
    tmp_fu_231_p1 = x_reg_198.read().range(13-1, 0);
}

void yuv2rgb::thread_tmp_s_fu_255_p2() {
    tmp_s_fu_255_p2 = (!p_shl2_cast_fu_235_p3.read().is_01() || !p_shl3_cast_fu_247_p3.read().is_01())? sc_lv<23>(): (sc_biguint<23>(p_shl2_cast_fu_235_p3.read()) + sc_biguint<23>(p_shl3_cast_fu_247_p3.read()));
}

void yuv2rgb::thread_x_1_fu_225_p2() {
    x_1_fu_225_p2 = (!x_reg_198.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(x_reg_198.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv2rgb::thread_y_1_fu_276_p2() {
    y_1_fu_276_p2 = (!y_reg_209.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(y_reg_209.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv2rgb::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_220_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_271_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

