// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module yuv2rgb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_channels_ch1_address0,
        in_channels_ch1_ce0,
        in_channels_ch1_q0,
        in_channels_ch2_address0,
        in_channels_ch2_ce0,
        in_channels_ch2_q0,
        in_channels_ch3_address0,
        in_channels_ch3_ce0,
        in_channels_ch3_q0,
        in_width_read,
        in_height_read,
        out_channels_ch1_address0,
        out_channels_ch1_ce0,
        out_channels_ch1_we0,
        out_channels_ch1_d0,
        out_channels_ch2_address0,
        out_channels_ch2_ce0,
        out_channels_ch2_we0,
        out_channels_ch2_d0,
        out_channels_ch3_address0,
        out_channels_ch3_ce0,
        out_channels_ch3_we0,
        out_channels_ch3_d0,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [21:0] in_channels_ch1_address0;
output   in_channels_ch1_ce0;
input  [7:0] in_channels_ch1_q0;
output  [21:0] in_channels_ch2_address0;
output   in_channels_ch2_ce0;
input  [7:0] in_channels_ch2_q0;
output  [21:0] in_channels_ch3_address0;
output   in_channels_ch3_ce0;
input  [7:0] in_channels_ch3_q0;
input  [15:0] in_width_read;
input  [15:0] in_height_read;
output  [21:0] out_channels_ch1_address0;
output   out_channels_ch1_ce0;
output   out_channels_ch1_we0;
output  [7:0] out_channels_ch1_d0;
output  [21:0] out_channels_ch2_address0;
output   out_channels_ch2_ce0;
output   out_channels_ch2_we0;
output  [7:0] out_channels_ch2_d0;
output  [21:0] out_channels_ch3_address0;
output   out_channels_ch3_ce0;
output   out_channels_ch3_we0;
output  [7:0] out_channels_ch3_d0;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_channels_ch1_ce0;
reg in_channels_ch2_ce0;
reg in_channels_ch3_ce0;
reg out_channels_ch1_ce0;
reg out_channels_ch1_we0;
reg out_channels_ch2_ce0;
reg out_channels_ch2_we0;
reg out_channels_ch3_ce0;
reg out_channels_ch3_we0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] x_1_fu_225_p2;
reg   [15:0] x_1_reg_580;
wire    ap_CS_fsm_state2;
wire   [22:0] tmp_s_fu_255_p2;
reg   [22:0] tmp_s_reg_585;
wire   [0:0] exitcond1_fu_220_p2;
wire   [15:0] y_1_fu_276_p2;
reg   [15:0] y_1_reg_593;
wire    ap_CS_fsm_state3;
wire   [63:0] tmp_21_cast_fu_291_p1;
reg   [63:0] tmp_21_cast_reg_598;
wire   [0:0] exitcond_fu_271_p2;
wire    ap_CS_fsm_state4;
reg   [7:0] Y_reg_622;
wire    ap_CS_fsm_state6;
wire  signed [7:0] D_fu_299_p2;
reg  signed [7:0] D_reg_627;
wire    ap_CS_fsm_state7;
wire  signed [7:0] E_fu_305_p2;
reg  signed [7:0] E_reg_634;
wire  signed [17:0] grp_fu_537_p4;
reg  signed [17:0] tmp_3_reg_639;
wire   [16:0] tmp_13_fu_315_p2;
reg   [16:0] tmp_13_reg_646;
wire   [7:0] R_fu_369_p3;
reg   [7:0] R_reg_651;
wire    ap_CS_fsm_state8;
wire   [7:0] G_fu_436_p3;
reg   [7:0] G_reg_656;
wire   [7:0] B_fu_529_p3;
reg   [7:0] B_reg_661;
wire    ap_CS_fsm_state9;
reg   [15:0] x_reg_198;
reg   [15:0] y_reg_209;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state5;
wire   [12:0] tmp_fu_231_p1;
wire   [14:0] tmp_5_fu_243_p1;
wire   [22:0] p_shl2_cast_fu_235_p3;
wire   [22:0] p_shl3_cast_fu_247_p3;
wire   [22:0] tmp_cast_fu_282_p1;
wire   [22:0] tmp_6_fu_286_p2;
wire  signed [7:0] tmp_13_fu_315_p1;
wire  signed [17:0] grp_fu_547_p3;
wire   [1:0] tmp_8_fu_324_p4;
wire   [0:0] icmp_fu_333_p2;
wire   [0:0] tmp_10_fu_339_p3;
wire   [0:0] tmp_11_fu_363_p2;
wire   [7:0] p_phitmp_fu_355_p3;
wire   [7:0] phitmp_fu_346_p4;
wire  signed [16:0] grp_fu_557_p3;
wire  signed [17:0] tmp1_cast_fu_380_p1;
(* use_dsp48 = "no" *) wire   [17:0] tmp_14_fu_383_p2;
wire   [1:0] tmp_15_fu_388_p4;
wire   [0:0] icmp9_fu_398_p2;
wire   [0:0] tmp_16_fu_404_p3;
wire   [0:0] tmp_17_fu_430_p2;
wire   [7:0] p_phitmp2_fu_422_p3;
wire   [7:0] phitmp2_fu_412_p4;
wire   [16:0] p_shl_fu_444_p3;
wire   [9:0] p_shl1_fu_455_p3;
wire  signed [17:0] p_shl1_cast_fu_462_p1;
(* use_dsp48 = "no" *) wire   [17:0] tmp2_fu_466_p2;
wire  signed [18:0] tmp2_cast_fu_471_p1;
wire  signed [18:0] p_shl_cast_fu_451_p1;
wire   [18:0] tmp_18_fu_475_p2;
wire   [2:0] tmp_19_fu_481_p4;
wire   [0:0] icmp1_fu_491_p2;
wire   [0:0] tmp_20_fu_497_p3;
wire   [0:0] tmp_21_fu_523_p2;
wire   [7:0] p_phitmp3_fu_515_p3;
wire   [7:0] phitmp3_fu_505_p4;
wire  signed [4:0] grp_fu_537_p0;
wire   [7:0] grp_fu_537_p1;
wire   [9:0] grp_fu_547_p0;
wire  signed [7:0] grp_fu_557_p0;
reg   [9:0] ap_NS_fsm;
wire   [8:0] grp_fu_537_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

yuv_filter_ama_adeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
yuv_filter_ama_adeOg_U15(
    .din0(grp_fu_537_p0),
    .din1(grp_fu_537_p1),
    .din2(18'd298),
    .din3(18'd128),
    .dout(grp_fu_537_p4)
);

yuv_filter_mac_mufYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
yuv_filter_mac_mufYi_U16(
    .din0(grp_fu_547_p0),
    .din1(E_reg_634),
    .din2(tmp_3_reg_639),
    .dout(grp_fu_547_p3)
);

yuv_filter_mac_mug8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
yuv_filter_mac_mug8j_U17(
    .din0(grp_fu_557_p0),
    .din1(D_reg_627),
    .din2(tmp_13_reg_646),
    .dout(grp_fu_557_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_271_p2 == 1'd1))) begin
        x_reg_198 <= x_1_reg_580;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        x_reg_198 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        y_reg_209 <= y_1_reg_593;
    end else if (((exitcond1_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_reg_209 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_reg_661 <= B_fu_529_p3;
        G_reg_656 <= G_fu_436_p3;
        R_reg_651 <= R_fu_369_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_reg_627 <= D_fu_299_p2;
        E_reg_634 <= E_fu_305_p2;
        tmp_13_reg_646 <= tmp_13_fu_315_p2;
        tmp_3_reg_639 <= grp_fu_537_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Y_reg_622 <= in_channels_ch1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_21_cast_reg_598[22 : 0] <= tmp_21_cast_fu_291_p1[22 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_585[22 : 8] <= tmp_s_fu_255_p2[22 : 8];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_1_reg_580 <= x_1_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_1_reg_593 <= y_1_fu_276_p2;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        in_channels_ch1_ce0 = 1'b1;
    end else begin
        in_channels_ch1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        in_channels_ch2_ce0 = 1'b1;
    end else begin
        in_channels_ch2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        in_channels_ch3_ce0 = 1'b1;
    end else begin
        in_channels_ch3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        out_channels_ch1_ce0 = 1'b1;
    end else begin
        out_channels_ch1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        out_channels_ch1_we0 = 1'b1;
    end else begin
        out_channels_ch1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        out_channels_ch2_ce0 = 1'b1;
    end else begin
        out_channels_ch2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        out_channels_ch2_we0 = 1'b1;
    end else begin
        out_channels_ch2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        out_channels_ch3_ce0 = 1'b1;
    end else begin
        out_channels_ch3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        out_channels_ch3_we0 = 1'b1;
    end else begin
        out_channels_ch3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_271_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_529_p3 = ((tmp_21_fu_523_p2[0:0] === 1'b1) ? p_phitmp3_fu_515_p3 : phitmp3_fu_505_p4);

assign D_fu_299_p2 = (in_channels_ch2_q0 ^ 8'd128);

assign E_fu_305_p2 = (in_channels_ch3_q0 ^ 8'd128);

assign G_fu_436_p3 = ((tmp_17_fu_430_p2[0:0] === 1'b1) ? p_phitmp2_fu_422_p3 : phitmp2_fu_412_p4);

assign R_fu_369_p3 = ((tmp_11_fu_363_p2[0:0] === 1'b1) ? p_phitmp_fu_355_p3 : phitmp_fu_346_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = in_width_read;

assign ap_return_1 = in_height_read;

assign exitcond1_fu_220_p2 = ((x_reg_198 == in_width_read) ? 1'b1 : 1'b0);

assign exitcond_fu_271_p2 = ((y_reg_209 == in_height_read) ? 1'b1 : 1'b0);

assign grp_fu_537_p0 = 9'd496;

assign grp_fu_537_p1 = grp_fu_537_p10;

assign grp_fu_537_p10 = Y_reg_622;

assign grp_fu_547_p0 = 18'd409;

assign grp_fu_557_p0 = 16'd65436;

assign icmp1_fu_491_p2 = (($signed(tmp_19_fu_481_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp9_fu_398_p2 = ((tmp_15_fu_388_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_fu_333_p2 = ((tmp_8_fu_324_p4 == 2'd1) ? 1'b1 : 1'b0);

assign in_channels_ch1_address0 = tmp_21_cast_fu_291_p1;

assign in_channels_ch2_address0 = tmp_21_cast_reg_598;

assign in_channels_ch3_address0 = tmp_21_cast_reg_598;

assign out_channels_ch1_address0 = tmp_21_cast_reg_598;

assign out_channels_ch1_d0 = R_reg_651;

assign out_channels_ch2_address0 = tmp_21_cast_reg_598;

assign out_channels_ch2_d0 = G_reg_656;

assign out_channels_ch3_address0 = tmp_21_cast_reg_598;

assign out_channels_ch3_d0 = B_reg_661;

assign p_phitmp2_fu_422_p3 = ((icmp9_fu_398_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_phitmp3_fu_515_p3 = ((icmp1_fu_491_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_phitmp_fu_355_p3 = ((icmp_fu_333_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_shl1_cast_fu_462_p1 = $signed(p_shl1_fu_455_p3);

assign p_shl1_fu_455_p3 = {{D_reg_627}, {2'd0}};

assign p_shl2_cast_fu_235_p3 = {{tmp_fu_231_p1}, {10'd0}};

assign p_shl3_cast_fu_247_p3 = {{tmp_5_fu_243_p1}, {8'd0}};

assign p_shl_cast_fu_451_p1 = $signed(p_shl_fu_444_p3);

assign p_shl_fu_444_p3 = {{D_reg_627}, {9'd0}};

assign phitmp2_fu_412_p4 = {{tmp_14_fu_383_p2[15:8]}};

assign phitmp3_fu_505_p4 = {{tmp_18_fu_475_p2[15:8]}};

assign phitmp_fu_346_p4 = {{grp_fu_547_p3[15:8]}};

assign tmp1_cast_fu_380_p1 = grp_fu_557_p3;

assign tmp2_cast_fu_471_p1 = $signed(tmp2_fu_466_p2);

assign tmp2_fu_466_p2 = ($signed(p_shl1_cast_fu_462_p1) + $signed(tmp_3_reg_639));

assign tmp_10_fu_339_p3 = grp_fu_547_p3[32'd17];

assign tmp_11_fu_363_p2 = (tmp_10_fu_339_p3 | icmp_fu_333_p2);

assign tmp_13_fu_315_p1 = E_fu_305_p2;

assign tmp_13_fu_315_p2 = ($signed(17'd130864) * $signed(tmp_13_fu_315_p1));

assign tmp_14_fu_383_p2 = ($signed(tmp1_cast_fu_380_p1) + $signed(tmp_3_reg_639));

assign tmp_15_fu_388_p4 = {{tmp_14_fu_383_p2[17:16]}};

assign tmp_16_fu_404_p3 = tmp_14_fu_383_p2[32'd17];

assign tmp_17_fu_430_p2 = (tmp_16_fu_404_p3 | icmp9_fu_398_p2);

assign tmp_18_fu_475_p2 = ($signed(tmp2_cast_fu_471_p1) + $signed(p_shl_cast_fu_451_p1));

assign tmp_19_fu_481_p4 = {{tmp_18_fu_475_p2[18:16]}};

assign tmp_20_fu_497_p3 = tmp_18_fu_475_p2[32'd18];

assign tmp_21_cast_fu_291_p1 = tmp_6_fu_286_p2;

assign tmp_21_fu_523_p2 = (tmp_20_fu_497_p3 | icmp1_fu_491_p2);

assign tmp_5_fu_243_p1 = x_reg_198[14:0];

assign tmp_6_fu_286_p2 = (tmp_cast_fu_282_p1 + tmp_s_reg_585);

assign tmp_8_fu_324_p4 = {{grp_fu_547_p3[17:16]}};

assign tmp_cast_fu_282_p1 = y_reg_209;

assign tmp_fu_231_p1 = x_reg_198[12:0];

assign tmp_s_fu_255_p2 = (p_shl2_cast_fu_235_p3 + p_shl3_cast_fu_247_p3);

assign x_1_fu_225_p2 = (x_reg_198 + 16'd1);

assign y_1_fu_276_p2 = (y_reg_209 + 16'd1);

always @ (posedge ap_clk) begin
    tmp_s_reg_585[7:0] <= 8'b00000000;
    tmp_21_cast_reg_598[63:23] <= 41'b00000000000000000000000000000000000000000;
end

endmodule //yuv2rgb
